#!/bin/bash

echo "🔍 检查 GitHub Actions 状态..."
echo ""
echo "请访问以下链接查看详细的失败日志："
echo "https://github.com/yalding8/aitest/actions"
echo ""
echo "常见失败原因："
echo "1. SSH 密钥过期或被更换"
echo "2. 服务器 authorized_keys 文件被修改"
echo "3. 服务器 IP 地址变更"
echo "4. GitHub Secrets 配置错误"
echo ""
echo "快速修复步骤："
echo "1. 生成新的部署密钥（无密码）："
echo "   ssh-keygen -t ed25519 -C 'github-deploy' -f ./github_deploy_key -N ''"
echo ""
echo "2. 将公钥添加到服务器："
echo "   cat github_deploy_key.pub"
echo "   # 然后 SSH 登录服务器，将公钥内容追加到 ~/.ssh/authorized_keys"
echo ""
echo "3. 更新 GitHub Secret SSH_PRIVATE_KEY："
echo "   cat github_deploy_key"
echo "   # 复制私钥全部内容（包括 BEGIN/END 行）"
echo "   # 访问: https://github.com/yalding8/aitest/settings/secrets/actions"
echo "   # 编辑 SSH_PRIVATE_KEY，粘贴新的私钥内容"
echo ""
